### ISSUE TITLE
Issue with ionic push in android device - EXCEPTION: Error: Uncaught (in promise): TypeError: push.on is not a function

### ISSUE THREAD

**Issue by harshgaur** [NishanthKabra/Ionic2-PushNotifications#4]
Hi Nishanth , I have gone through your article and I really want to thank you for your efforts.
I followed each and every step according to your blog and also cloned your git code fo implement the push.
But unfortunately I was not able to implement it, I am facing errors as below - 
Here is the complete console output - 
0     718978   log      Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
1     719943   log      DEVICE READY FIRED AFTER, 1469, ms
2     719948   warn     Native: tried calling Push.init, but the Push plugin is not installed.
3     719948   warn     Install the Push plugin: 'ionic plugin add phonegap-plugin-push'
4     719967   group    EXCEPTION: Error: Uncaught (in promise): TypeError: push.on is not a function
5     719968   error    EXCEPTION: Error: Uncaught (in promise): TypeError: push.on is not a function
6     719968   error    STACKTRACE:
7     719969   error    Error: Uncaught (in promise): TypeError: push.on is not a function
    at resolvePromise (http://192.168.1.7:8100/build/js/angular2-polyfills.js:602:32)
    at http://192.168.1.7:8100/build/js/angular2-polyfills.js:638:18
    at ZoneDelegate.invokeTask (http://192.168.1.7:8100/build/js/angular2-polyfills.js:423:38)
    at Object.onInvokeTask (http://192.168.1.7:8100/build/js/app.bundle.js:27197:41)
    at ZoneDelegate.invokeTask (http://192.168.1.7:8100/build/js/angular2-polyfills.js:422:43)
    at Zone.runTask (http://192.168.1.7:8100/build/js/angular2-polyfills.js:320:48)
    at drainMicroTaskQueue (http://192.168.1.7:8100/build/js/angular2-polyfills.js:541:36)
    at ZoneTask.invoke (http://192.168.1.7:8100/build/js/angular2-polyfills.js:493:22)
8     719970   groupEnd 
9     719972   error    Unhandled Promise rejection:, push.on is not a function, ; Zone:, angular, ; Task:, Promise.then, ; Value:, [object Object]

**Comment by NishanthKabra** [comment]
looks like your are trying to test it on browser and push doesnt exist there. Deploy it to real device and then things should be working fine.
